### ISSUE TITLE
A Proper HTML Table

### ISSUE THREAD

**Issue by DahliaSR** [CheckiO-Missions/checkio-task-roman-numerals#11]
- [x] include **all** translations

![image](https://cloud.githubusercontent.com/assets/19154016/24515347/a495e682-1577-11e7-8261-5c52d00cf445.png)

@oduvan Ignore this issue, I just need to track it somewhere.  
It will be closed once you merge the pull request that will follow.

**Comment by oduvan** [comment]
Sure
